apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Pipeline
spec:
  tasks:
  - name: echo
    params:
    - name: echo2
      value: "$(params.echo)"
    taskSpec:
      params:
      - name: echo2
      steps:
      - image: ubuntu
        script: |
          echo -n "$(params.echo2)"
