apiVersion: tekton.dev/v1
kind: Pipeline
spec:
  params:
  - name: echo
  tasks:
  - name: echo
    params:
      - name: echo
    taskSpec:
      params:
      - name: echo
      steps:
      - image: ubuntu
        script: |
          echo -n "$(params.echo)"
