apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: param-ref
spec:
  params:
    - name: echo
  tasks:
  - name: echo
    params:
    - name: echo2
      value: "$(params.echo)"
    taskSpec:
      params:
      - name: echo2
      steps:
      - name: test
        image: ubuntu
        script: |
          echo -n "$(params.echo2)"
